version: "3.3"
services: 
  gamma-gateway:
    image: ghcr.io/takahiro55555/gamma-gateway:latest
    container_name: "gamma-gateway"
    env_file:
      - .env
    environment:
      level: debug
      caller: "false"
      # managerHost: mqtt-broker
      # managerPort: "1883"
      # gatewayHost: mqtt-broker  # 同一の Docker network で動作するコンテナ名(ホスト名、Docker側が名前解決)
      # gatewayPort: "1883"
      env: production
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 1m

  mqtt-broker:
    image: eclipse-mosquitto:1.6
    container_name: "mqtt-broker"
    ports: 
      - 1883:1883
      - 9001:9001
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 1m

networks:
  default:
    driver: bridge
