version: "3.3"
services: 
  gamma-dmb:
    image: ghcr.io/takahiro55555/gamma-dmb:latest
    container_name: "gamma-dmb"
    env_file:
      - .env
    environment:
      env: "production"
      level: "info"
      caller: "false"
      # managerHost: "mqtt-broker"
      # managerPort: "1883"
      dmbHost: "mqtt-broker"  # 同一の Docker network で動作するコンテナ名(ホスト名、Docker側が名前解決)
      dmbPort: "1883"
      dmbTopic: "/"
      baseRetransmissionIntervalMilliSeconds: "10"
      maxRetransmissionIntervalMilliSeconds: "5000"
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 1m

  mqtt-broker:
    image: eclipse-mosquitto:1.6
    container_name: "mqtt-broker"
    ports: 
      - 1883:1883
      - 9001:9001
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 1m

networks:
  default:
    driver: bridge
